# Semantic Search
semanticsearch:
  openAIKey: # your openAI key
  pineconeKey: # your pinecone key
  pineconeUrl: # your pinecone url. e.g: https://api.pinecone.io
  pineconeNamespace: # your name, without spaces. e.g: agilemonkey

# Spring Boot
springdoc:
  swagger-ui:
    path: /docs

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB